---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Alexandra Garcia AG65597"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
```

# Modeling 
```{R}
#LEAVE THIS CHUNK ALONE!
library(knitr)
opts_chunk$set(fig.align="center", fig.height=5, message=FALSE, warning=FALSE, fig.width=8, tidy.opts=list(width.cutoff=60),tidy=TRUE)

class_diag<-function(probs,truth){
  
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}



```

# INTRODUCTION

- **0. (5 pts)** Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?

```{R}
hep <- read_csv("hep.csv")
# Remove all rows with NAs
hep <- na.omit(hep)
hep$Category[which(hep$Category == "0=Blood Donor")] = "blood_donor"
hep$Category[which(hep$Category == "3=Cirrhosis")] = "cirrhosis"
hep$Category[which(hep$Category == "1=Hepatitis")] = "hepatitis"
hep$Category[which(hep$Category == "2=Fibrosis")] = "fibrosis"
hep <- hep %>% filter(Category != "0s=suspect Blood Donor")

hep %>% group_by(Category) %>% count()
```


The hep dataset contains clinical and demographic characteristics of blood donors and hepatitis C patients. Numeric variables include age, albumin blood, alkaline phosphatase, alanine transaminase, aspartate transaminase, bilirubin, acetylcholinesterase, cholesterol, creatinine, gamma-glutamyl transferase, and protein levels. Categorical variables include the disease category, if any, to which each person falls into (blood donor, hepatitis C, cirrhosis, and firbosis) and sex composing of male and female. After removing all NAs, there are 526 blood donors, 24 cirrhosis patients, 12 fibrosis patients, and 20 hepatitis patients, for a total number 582 participants.



# MANOVA

- **1. (15 pts)** 
```{R}
manova_hep <- manova(cbind(ALB, ALP, AST, BIL, CHOL)~Category,data=hep)
summary(manova_hep)
summary.aov(manova_hep)

# Perform post-hoc test for 5 ANOVAs
pairwise.t.test(hep$ALB, hep$Category, p.adj="none")
pairwise.t.test(hep$ALP, hep$Category, p.adj="none")
pairwise.t.test(hep$AST, hep$Category, p.adj="none")
pairwise.t.test(hep$BIL, hep$Category, p.adj="none")
pairwise.t.test(hep$CHOL, hep$Category, p.adj="none")

# Type I error probability
1 - (0.95^36)

# bonferroni
0.05/36
```

  After performing a MANOVA test, at least one of the 5 response variables differ by Category (p<0.05). To test for which response variable differs by Category, a post-hoc test was conducted where we saw that all albumin blood, alkaline phosphatase, aspartate transaminase, bilirubin, and cholesterol differ by Category (blood donor, hepatitis C, cirrhosis, and firbosis patient). However this was done prior to adjusting the significance level. In total, 36 hypothesis tests were conducted. The probability of making a type I error is  0.8422208. A 0.001388889 significance level should be used to keep the overall type I error rate at .05 (bonferroni adjusted). It is probable that most, if not all, MANOVA assumptions are violated.

  Using the adjusted significance level, there is a significant mean difference in albumin blood levels between cirrhosis patients and normal blood donor, fibrosis and cirrhosis patients,and  hepatitis C and cirrhosis patients. There is also a significant mean difference in alkaline phosphatase levels for all category group comparison except for hepatitis C and fibrosis patients. A mean difference in aspartate transaminase levels for all category group comparison except for hepatitis C and fibrosis patients and fibrosis and cirrhosis patients. For bilirubin levels, there is a significant mean difference for cirrhosis patients and blood donors, cirrhosis and fibrosis patients, and hepatitis C and cirrhosis patients. Finally, there is a significant mean difference in cholesterol levels for only cirrhosis patients and blood donors, and cirrhosis and hepatitis C patients.




- **2. (10 pts)** 
```{R}
# H0: mean bilirubin levels are the same for fibrosis and cirrhosis patients
fib <- hep %>% select(Category, BIL) %>% filter(Category=="fibrosis")
cir <- hep %>% select(Category, BIL) %>% filter(Category=="cirrhosis")

fib_cir <- full_join(fib,cir)

t.test(fib$BIL, cir$BIL)

# mean BIL difference between fibrosis and cirrhosis patients
60.50 -14.16667

rand_dist<-vector()
for(i in 1:5000){
new<-data.frame(BIL=sample(fib_cir$BIL),Category=fib_cir$Category)
rand_dist[i]<-mean(new[new$Category=="cirrhosis",]$BIL)-   
              mean(new[new$Category=="fibrosis",]$BIL)}

# two-tailed p-value BIL
mean(rand_dist>46.33333 | rand_dist< -46.33333)

{hist(rand_dist,main="",ylab=""); abline(v = c(-46.33333, 46.33333),col="red")}
```
Using a Welch Two Sample t-test, mean bilirubin levels for fibrosis and cirrhosis patients are 14.167 and 60.50, respectively. The mean difference between the two number was 46.33. A randomization test was then conducted to test whether mean bilirubin levels are the same for fibrosis and cirrhosis patients (null hypothesis) because both groups have small sample sizes. A p-value of 0.0138 was obtained from the randomization test, therefore we can reject the null hypothesis. There is a significant mean difference in bulirubin levels for fibrosis and cirrhosis patients.




# LINEAR REGRESSION

- **3. (40 pts)** 
    
```{R}
# Mean center numeric variable alkaline phosphate (ALP)
hep_c <- hep %>% mutate(ALP_c=ALP - mean(ALP,na.rm=T))

# linear model predicting Albumin blood levels from alkaline phosphate (ALP) and Category
linmod_hep_c <- lm(ALB ~ ALP_c * Category, data=hep_c)
summary(linmod_hep_c)
```

Our R-squared is 0.1499, which is the proportion of variation that our model can explain. Albumin blood levels for a normal blood donor is 42.188 g/L with an average alkaline phosphate level. For every 1-unit increase in alkaline phosphate level for a normal blood donor, albumin level decreases 0.0005053 g/L. Those with a Cirrhosis diagnosis with an average alkaline phosphate level have an albumin level 10.20 g/L lower than normal blood donors.Those with a Fibrosis diagnosis with an average alkaline phosphate level have an albumin level 0.912 g/L lower than normal blood donors. Next,those with a Hepatitis C diagnosis and with an average alkaline phosphate level have an albumin level 0.207 g/L higher than normal blood donors. Finally, the slope of alkaline phosphate on albumin level for those with Cirrhosis, Fibrosis, and Hepatitis C is 0.0007037,0.0573043, and 0.0454149 less than for normal blood donors, respectively.



```{R}
# LINEAR REGRESSION GRAPH
ggplot(hep_c, aes(ALP_c,ALB, color = Category)) + geom_smooth(method = "lm", se = F, fullrange = T)+geom_point()+geom_vline(xintercept=0,lty=2)

```

```{R}
# Homoskedasticity
library(lmtest)
library(sandwich)
bptest(linmod_hep_c)

resids<-linmod_hep_c$residuals

# Normality 
ks.test(resids, "pnorm", mean=0, sd(resids))

fitted<-lm(ALB ~ ALP_c * Category, data=hep_c)$fitted.values
ggplot()+geom_point(aes(fitted,resids))
```
After conducting the Breusch-Pagan test for homoskedasticity on the linear model, we can conclude that the model meets the homoskedasticity assumption (p=0.943). After also conducting the Kolmogorov-Smirnov test to check for normality, we can say our model meets the normality assumption (p=0.10). However, by plotting the residuals against the fitted values, it does not appear that there is a linear relationship.



```{R}
# recompute regression with robust SEs
coeftest(linmod_hep_c, vcov = vcovHC(linmod_hep_c))
```

After computing the regression model with robust standard errors, there was no difference in the coefficient estimates compared to the previously run regression model. There was only one significant coefficient in the regression model. Those with a Cirrhosis diagnosis with an average alkaline phosphate level have an albumin level 10.20 g/L lower than normal blood donors (p<0.05).



- **4. (5 pts)** 

```{R}
# Resampling Residuals
fit<-lm(ALB ~ ALP_c * Category, data=hep_c)
  resids<-fit$residuals
  fitted<-fit$fitted.values
  
  resid_resample<-replicate(5000,{
    new_resids<-sample(resids,replace=TRUE)
    hep_c$new_ALB<-fitted+new_resids 
    fit<-lm(new_ALB ~ ALP_c * Category, data=hep_c)
    coef(fit)
})

resid_resample%>%t%>%as.data.frame%>%summarize_all(sd)
```


There were some slight changes in bootstrapped SEs from the original and robust SEs. The bootstrapped SEs for cirrhosis and fibrosis were lower than their original SEs. Likewise, the bootstrapped SEs for cirrhosis and hepatitis C were lower than the robust SEs. Fibrosis bootstrapped SE was much greater than the robust SE. Finally, the bootstrap SE for the interaction between alkaline phosphatase level and fibrosis status is greater than the robust SE for the interaction.



# LOGISTIC REGRESSION

- **5. (30 pts)** 
    
```{R}
hep <- hep %>% mutate(sex_bin =ifelse(Sex=="m",1,0))
hep <- hep %>% mutate(diag =ifelse(Category=="blood_donor",0,1))

fit_hep <- glm(diag~sex_bin+BIL + CHE, data=hep, family="binomial")
summary(fit_hep)
exp(coef(fit_hep)) %>% round(3)

```
The logistic regression model is predicting whether someone is or is not diagnosed with a liver disease (hepatitis, cirrhosis, or fibrosis) from bilirubin level, acetylcholinerase level, and sex. 

The odds of disease diagnosis for females with a bilirubin level of 0 is 0.086. When controlling for bilirubin level and , the odds of disease diagnosis for males is 1.257 times the odds of disease diagnosis for females, however it is not significant (p=0.54). When controlling for sex and acetylcholinerase level, for every 1-unit increase in bulirubin level, the odds of disease diagnosis for females increases by a factor of 1.102 (p<0.05). When controlling for bilirubin and sex, for every 1-unit increase in acetylcholinerase level, the odds of disease diagnosis for females increases by a factor of 0.854 (p<0.05). 


```{R}
probs<-predict(fit_hep,type="response") 
table(predict=as.numeric(probs>.5),truth=hep$diag)%>%addmargins #0.5 is cutoff for disease diagnosis

class_diag(probs, hep$diag)
```

Our model has an AUC of 0.806, which is considered "good". However, the model has a low sensitivity of 0.304; But the specificity is high, with a proportion of 0.99. The accuracy of our model is 0.924 and the precision is 0.773.



```{R}
#density plot of the log-odds (logit) colored/grouped by your binary diagnosis variable
hep$logit<-predict(fit_hep,type="link") #get predicted logit scores (logodds)

hep %>% mutate(diag=as.factor(diag)) %>% ggplot() + geom_density(aes(logit, fill=diag, color=diag), alpha=.4) + theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab("predictor (logit)")

```



- **6. (25 pts)** 

```{R}
hep_all <- hep %>% select(diag,Age,sex_bin,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT)

fit_hep_all <- glm(diag~., data=hep_all, family="binomial")
proby <- predict(fit_hep_all, type="response")
class_diag(proby, hep_all$diag)

```

After performing a logistic regression predicting diagnosis status from all other variables, our calculated AUC is 0.995, which is considered "great". The sensitivity and specificity are 0.929 and 0.996, respectively. Accuracy was calculated to be 0.9897. Precision was 0.963.


```{R}
# 10-fold CV on model
set.seed(1234)
k=10

data<-hep_all[sample(nrow(hep_all)),]
folds<-cut(seq(1:nrow(hep_all)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
  train<-data[folds!=i,]   
  test<-data[folds==i,]  
  truth<-test$diag
  fit<-glm(diag~.,data=train,family="binomial")   
  probs<-predict(fit,newdata = test,type="response")
  diags<-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)
```

After performing the 10-fold cross validation on the logistic regression model predicting diagnosis status from all other variables, our newly calculated AUC is 0.962, which is still considered "great". However, the decrease in AUC from 0.99 to 0.96 indicates overfitting. The newly calculated sensitivity and specificity are 0.812 and 0.992, respectively. Accuracy was calculated to be 0.974. Precision was 0.928.


```{R}
# LASSO
library(glmnet)
set.seed(1234)

y<-as.matrix(hep_all$diag)
x<-model.matrix(diag~.,data=hep_all)[,-1]

cv <- cv.glmnet(x, y, family="binomial")
lasso <- glmnet(x, y, family="binomial", lambda = cv$lambda.1se)
coef(lasso)

lasso_dat <- hep_all
lasso_dat_fit <- glm(diag~., data=lasso_dat, family="binomial")

prob_lasso <- predict(lasso_dat_fit, type="response")
```

According to the LASSO that was run, the variables that were retained were alkaline phosphatase level (ALP), alanine transaminase level (ALT), Aspartate Transaminase level(AST), Bilirubin level (BIL), cholesterol (CHOL), creatine (CREA), and Gamma-Glutamyl Transferase(GGT)




```{R}
# 10-fold CV on LASSO variables

set.seed(1234)
k=10
data<-lasso_dat[sample(nrow(lasso_dat)),]
folds<-cut(seq(1:nrow(lasso_dat)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
  train<-data[folds!=i,]   
  test<-data[folds==i,]  
  truth<-test$diag
  fit<-glm(diag~.,data=train,family="binomial")   
  probs<-predict(fit,newdata = test,type="response")
  diags<-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)
```


The model's out-of-sample AUC is much greater than the AUC calculated from the above logistic regression. The AUC increased from a "good" value of 0.806 to a "great" value 0.962. 


...





